# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nle2MWEmmMuNDtkO3uNay7TwS2G4CKuY
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

# Load dataset
file_path = "Data Collection - Task 1 - Sheet1.csv"   # change path if needed
df = pd.read_csv(file_path)

# Clean dataset
df = df.dropna(how="all")
df.columns = df.columns.str.strip()

# Initialize vectorizer
vectorizer = CountVectorizer()

# Fit and transform comments
X = vectorizer.fit_transform(df["Comments"].astype(str))

# Convert to DataFrame for readability
vectorized_df = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())

# Show first few rows
print(vectorized_df.head())

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df["Comments"].astype(str))

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Load dataset
file_path = "Data Collection - Task 1 - Sheet1.csv"   # change path if needed
df = pd.read_csv(file_path)

# Clean dataset
df = df.dropna(how="all")
df.columns = df.columns.str.strip()

# Features (X) and Labels (y)
X = df["Comments"].astype(str)
y = df["Reviews"].astype(str)

# Vectorize using TF-IDF
vectorizer = TfidfVectorizer()
X_vec = vectorizer.fit_transform(X)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X_vec, y, test_size=0.2, random_state=42
)

# ======================
# Models to Train
# ======================
models = {
    "Naive Bayes": MultinomialNB(),
    "SVM": SVC(kernel="linear"),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42)
}

results = {}

# Train & Evaluate Each Model
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    results[name] = acc
    print(f"\n===== {name} =====")
    print("Accuracy:", acc)
    print(classification_report(y_test, y_pred))

# Find Best Model
best_model_name = max(results, key=results.get)
print("\n Best Model:", best_model_name, "with Accuracy:", results[best_model_name])